<?php
/**
 * Created by PhpStorm.
 * User: 李政宇
 * Date: 2017/6/29
 * Time: 11:26
 */
namespace frontend\controllers;
use backend\models\Goods;
use backend\models\PasswordForm;
use frontend\models\Area;
use frontend\models\Member;
use yii\web\Controller;
use yii\web\Response;


class ApiController extends Controller{
    public $enableCsrfValidation=false;//关闭跨站攻击验证
    public function init()
    {
        \Yii::$app->response->format=Response::FORMAT_JSON;
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function actionGetGoods(){
        $brand_id=\Yii::$app->request->get('brand_id');
        $goods=Goods::findAll(['brand_id'=>$brand_id]);
        if($goods==null){
            return ['status'=>-1,'errormsg'=>'商品不存在','data'=>""];
        }
        return ['status'=>1,'errormsg'=>"",'data'=>$goods];

    }
    public function actionRegister(){
        $request=\Yii::$app->request;
        if($request->isPost){
            $user=new Member();
            $user->username=$request->post('username');
            $user->password=$request->post('password');
            $user->email=$request->post('email');
            $user->tel=$request->post('tel');
            if($user->validate()){
                $user->save();
                return ['status'=>'1','msg'=>'','data'=>$user->toArray()];
            }
            return ['status'=>'-1','msg'=>$user->getErrors()];
        }
        return ['status'=>'-1','msg'=>'请使用post请求'];
    }
    public function actionLogin(){
        $request=\Yii::$app->request;
        if($request->isPost){
            $user=Member::findOne(['username'=>$request->post('username')]);
            if($user && \Yii::$app->security->validatePassword($request->post('password'),$user->password_hash)){
                \Yii::$app->user->login($user);
                return ['status'=>1,'msg'=>'登陆成功'];
            }
            return['status'=>-1,'msg'=>'用户名或密码不正确'];

        }
        return ['status'=>-1,'msg'=>'请使用post请求'];
    }
    public function actionUppassword(){
        $request=\Yii::$app->request;
        if(\Yii::$app->user->isGuest){
            return ['status'=>0,'msg'=>'未登陆，请登陆'];
            return $this->redirect(['user/login']);
        }
        if($request->isPost){
            $model=new PasswordForm();
            $model->oldpassword=$request->post('oldpassword');
            $model->newpassword=$request->post('newpassword');
            $model->repassword=$request->post('repassword');
            if($model->validate()){
                $user=\Yii::$app->user->identity;
                $user->password_hash=$model->newpassword;
                $user->save();
                return ['status'=>1,'msg'=>'密码修改成功'];
            }
            return ['status'=>-1,'msg'=>$model->getErrors()];

        }
    }
    public function actionGetUser(){
        if(\Yii::$app->user->isGuest){
            return ['status'=>0,'msg'=>'未登陆，请登陆'];
            return $this->redirect(['user/login']);
        }
        return ['status'=>1,"msg"=>"","data"=>['username'=>\Yii::$app->user->identity->username,'id'=>\Yii::$app->user->getId()]];
    }
    public function actionAddaddress(){
        if(\Yii::$app->user->isGuest){
            return ['status'=>0,'msg'=>'未登陆，请登陆'];
            return $this->redirect(['user/login']);
        }
        $model=new Area();
        $areas=Area::findAll(['member_id'=>\Yii::$app->user->id]);
        $request=\Yii::$app->request;
        if($request->isPost){
            $model->user_name=$request->post('name');
            $model->province=$request->post('province');
            $model->city=$request->post('city');
            $model->district=$request->post('district');
            $model->tel=$request->post('tel');
            $model->content=$request->post('content');
            $model->is_mo=$request->post('is_mo');
            if($model->validate()){
              if($model->is_mo){
                  foreach ($areas as $area){
                      $area->is_mo=0;
                      $area->save();
                  }
              }
              $model->member_id=\Yii::$app->user->id;
              $model->save();
              return ['status'=>1,'msg'=>'添加地址成功'];

            }
            return ['status'=>-1,'msg'=>$model->getErrors()];
        }
    }
    public function actionTest(){
       $weathers=simplexml_load_file('http://flash.weather.com.cn/wmaps/xml/sichuan.xml');
       $data=[];
        foreach ($weathers as $k=>$weather){
            if($weather['cityname']=='成都'){
                echo '成都天气情况：'.$weather['stateDetailed'].'最高温度：'.$weather['tem1'].'最低温度：'.$weather['tem2'];
            }

        }
    }

}