<?php
/**
 * Created by PhpStorm.
 * User: 李政宇
 * Date: 2017/6/22
 * Time: 16:31
 */
namespace frontend\widgets;
use yii\base\Widget;

class CategoryWidgets extends Widget{
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }
    public function run()
    {
        $redis=new \Redis();
        $redis->connect('127.0.0.1');
        $category_html=$redis->get('category_html');
        if($category_html==null){
            $goods_categorys=\backend\models\GoodsCategory::find()->where(['parent_id'=>0])->all();
            $category_html=$this->render('@app/widgets/view/category.php',['goods_categorys'=>$goods_categorys]);
            $redis->set('category_html',$category_html);
        }
        return $category_html;

    }
}