<?php
/**
 * Created by PhpStorm.
 * User: 李政宇
 * Date: 2017/6/18
 * Time: 15:24
 */
namespace backend\filetr;
use yii\base\ActionFilter;
use yii\web\HttpException;

class RbacFilter extends ActionFilter{
    public function beforeAction($action)
    {
        $user=\Yii::$app->user;
        if(!$user->can($action->uniqueId)){
            if($user->isGuest){
                return $action->controller->redirect($user->loginUrl);
            }
           throw  new HttpException(403,'对不起，你没有权限访问该页面');
            return false;
        }
        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }
}